### ISSUE TITLE
Correctly manage connection reuse

### ISSUE THREAD

**Issue by jcea** [zabuldon/easywebdav#3]
Although technically "requests" library allows connection reuse, current use in "easywebdav2" precludes it.

The reason is simple: The requests session is tagged as "stream=True" and:

1. Most of the time, the body is not read at all, only the status code is checked. Since the body is not read and "stream=True", the connection can NOT be reused.

2. Even when the body is read, like in "download", we must call "req.close()" explicitly to give the connection back to the pool.

Suggestion:

1. Do NOT create the session with "stream=True". In this way, the request is completely read and the connection is back to the pool automatically.

2. In the few cases that stream reading is convenient, like in "download", do a "stream=True" request explicitly and manage it correctly.

If you agree with this plan, I can provide a pull request.

Thanks.

**Comment by zabuldon** [comment]
Sounds reasonable. I'm ok with both suggestions. Feel free top open PR.

**Comment by zabuldon** [comment]
By the way I see another approach already suggested to original lib: https://github.com/amnong/easywebdav/pull/59/commits/8f1408cb959239b9e1301357b1d454962065e2b1

**Comment by jcea** [comment]
That patch is incomplete (for instance, "download" will not reuse connection) and far more intrusive and non obvious that my proposal.

I will create a pull request.

**Comment by zabuldon** [comment]
PR merged.
